server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:29092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF